---
admin_user: { uid: 1000, name: vagrant, system: no }

ansible_ssh_user: vagrant 
ansible_ssh_private_key_file: ~/.ssh/id_rsa

docker_version: "17.03"
docker_user: "{{ admin_user.name }}"
docker_compose_version: "1.21.1"

app_dir: "/home/vagrant/app"