---
- name: down grpc-server with db
  command: docker-compose --file compose-grpc-server.yml down
  args:
    chdir: "{{ app_dir }}"

- name: deploy grpc-server with db
  command: docker-compose --file compose-grpc-server.yml up -d
  args:
    chdir: "{{ app_dir }}"
