---
- name: install docker-compose
  command: "{{ item }}"
  with_items:
    - "wget https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    - "mv docker-compose-Linux-x86_64 /bin/docker-compose"
    - "chmod +x /bin/docker-compose"
