---
- name: down client
  command: docker-compose --file compose-client.yml down
  args:
    chdir: "{{ app_dir }}"

- name: deploy client
  command: docker-compose --file compose-client.yml up -d
  args:
    chdir: "{{ app_dir }}"
